export const quests = {
  technology: [
    {
      quest: "Kiedy odbyła się oficjalna pierwsza prezentacja telewizora?",
      answer: ["1926", "1984", "1912", "1950"],
      correct: "1926",
      incorrect: [null, "1984", "1912", "1950"],
      type: "closed",
    },
    {
      quest: "Kto jest założycielem Tesli?",
      answer: [
        "Elon Musk",
        "Silvester Stalone",
        "Albert Einstein",
        "Mark Zuckenberg",
      ],
      correct: "Elon Musk",
      incorrect: [
        null,
        "Silvester Stalone",
        "Albert Einstein",
        "Mark Zuckenberg",
      ],
      type: "closed",
    },
    {
      quest: "W którym roku powstał Bitcoin?",
      answer: null,
      correct: "2009",
      type: "input",
    },
    {
      quest: "Jaką nosił nazwę pierwszy zaprojektowany komputer?",
      answer: ["Toshiba", "Siemens", "Eniac", "Kodiak"],
      correct: "Eniac",
      incorrect: ["Toshiba", "Siemens", null, "Kodiak"],
      type: "closed",
    },
    {
      quest: "Apollo 11, taką nazwę miała misja lotu na księżyc?",
      answer: ["Tak", "Nie"],
      correct: "Tak",
      incorrect: [null, "Nie"],
      type: "closed",
    },
    {
      quest: "Kto jest założycielem Micosoftu?",
      answer: ["Bill Gates", "Steven Hawkins", "John Travis"],
      correct: "Bill Gates",
      incorrect: [null, "Steven Hawkins", "John Travis"],
      type: "closed",
    },
    {
      quest: "Najnowsza generacja konsol Sony to:",
      answer: ["PlayStation 5", "Xbox 360", "Nintendo", "MAC"],
      correct: "PlayStation 5",
      incorrect: [null, "Xbox 360", "Nintendo", "MAC"],
      type: "closed",
    },
    {
      quest: "Pierwszy układ scalony został stworzony w XX wieku których lat?",
      answer: ["50", "60", "70", "80"],
      correct: "50",
      incorrect: [null, "60", "70", "80"],
      type: "closed",
    },
    {
      quest: "Kto jako pierwszy wynalazł i opatentował żarówkę?",
      answer: [
        "Joseph Wilson Swan",
        "Thomas Alva Edison",
        "Nikola Tesla",
        "Mikołaj Kopernik",
      ],
      correct: "Joseph Wilson Swan",
      incorrect: [
        null,
        "Thomas Alva Edison",
        "Nikola Tesla",
        "Mikołaj Kopernik",
      ],
      type: "closed",
    },
    {
      quest: "W jakim celu został stworzony Internet?",
      answer: ["Militaria", "Komunikacja", "Rozrywka", "Medycyna"],
      correct: "Militaria",
      incorrect: [null, "Komunikacja", "Rozrywka", "Medycyna"],
      type: "closed",
    },
  ],
  moto: [
    {
      quest: "Ułóż od najstarszego do najnowszego",
      answer: ["E39", "E46", "E75", "E35"],
      correct: ["E35", "E39", "E46", "E75"],
      type: "drag",
    },
    {
      quest: "Czy AUDI jest samochodem niemieckiej produkcji?",
      answer: ["Tak", "Nie"],
      correct: "Tak",
      incorrect: [null, "Nie"],
      type: "closed",
    },
    {
      quest:
        "Jaki samochód pierwotnie miał służyć jako limuzyna rządowa w Czechach?",
      answer: ["Fiat", "Audi", "Skoda", "Chevrolet"],
      correct: "Skoda",
      incorrect: ["Fiat", "Audi", null, "Chevrolet"],
      type: "closed",
    },
    {
      quest:
        "Ile turbosprężarek fabrycznie zamontowanych jest w Mitsubishi Galant?",
      answer: ["Jedna", "Dwie", "Trzy", "Cztery"],
      correct: "Dwie",
      incorrect: ["Jedna", null, "Trzy", "Cztery"],
      type: "closed",
    },
    {
      quest: "TDI to słynny silnik na cały świat napędzany:",
      answer: ["Benzyną", "Ropą", "Gazem", "Prądem"],
      correct: "Ropą",
      incorrect: ["Benzyną", null, "Gazem", "Prądem"],
      type: "closed",
    },
    {
      quest: "Ułóż od najmniejszego do największego",
      answer: ["SUV", "Sedan", "TIR", "Hatchback"],
      correct: ["Hatchback", "Sedan", "SUV", "TIR"],
      type: "drag",
    },
    {
      quest: "Potocznie nazywany maluch to?",
      answer: ["Fiat", "Chevrolet", "Syrena", "Trabant"],
      correct: "Fiat",
      incorrect: [null, "Chevrolet", "Syrena", "Trabant"],
      type: "closed",
    },
    {
      quest: "Zawór recyrkulacji gazu to inaczej?",
      answer: ["Zawór BEM", "Zawór EGR", "Zawór gazu", "Zawór paliwa"],
      correct: "Zawór EGR",
      incorrect: ["Zawór BEM", null, "Zawór gazu", "Zawór paliwa"],
      type: "closed",
    },
    {
      quest:
        "Co jest prawdopodbnie uszkodzone, jeśli wskazówka obrotomierza faluje na niskich obrotach?",
      answer: ["Silnik krokowy", "Kierunkowskaz", "Tarcze hamulcowe", "Tłumik"],
      correct: "Silnik krokowy",
      incorrect: [null, "Kierunkowskaz", "Tarcze hamulcowe", "Tłumik"],
      type: "closed",
    },
    {
      quest: "Jaki kraj wykupił Fiata od Polski?",
      answer: ["Włochy", "Hiszpania", "Portugalia", "Francja"],
      correct: "Włochy",
      incorrect: [null, "Hiszpania", "Portugalia", "Francja"],
      type: "closed",
    },
  ],
  history: [
    {
      quest: "W którym roku miała miejsce bitwa pod Grunwaldem?",
      answer: ["1412", "1411", "1410", "1525"],
      correct: "1410",
      incorrect: ["1412", "1411", null, "1525"],
      type: "closed",
    },
    {
      quest: "Kto oficjalnie jest uznawany za odkrywcę Ameryki?",
      answer: ["Karol Marks", "Krzysztof Kolumb", "Isaac Newton", "Napoleon"],
      correct: "Krzysztof Kolumb",
      incorrect: ["Karol Marks", null, "Isaac Newton", "Napoleon"],
      type: "closed",
    },
    {
      quest: "Jaki kraj nie uczestniczył w robiorach Polski?",
      answer: ["Niemcy", "Austria", "Rosja", "Czechy"],
      correct: "Czechy",
      incorrect: ["Niemcy", "Austria", "Rosja", null],
      type: "closed",
    },
    {
      quest: "Uporządkuj chronologicznie wydarzenia:",
      answer: [
        "Bitwa pod Grunwaldem",
        "II Wojna Światowa",
        "Chrzest Polski",
        "Rozbiory Polski",
      ],
      correct: [
        "Chrzest Polski",
        "Bitwa pod Grunwaldem",
        "Rozbiory Polski",
        "II Wojna Światowa",
      ],
      type: "drag",
    },
    {
      quest: "W którym roku miał miejsce chrzest Polski?",
      answer: null,
      correct: "966",
      type: "input",
    },
    {
      quest: "Z jakim krajem Polska miały Unię Personalną?",
      answer: ["Rosja", "Litwa", "Niemcy", "Państwo Osmańskie"],
      correct: "Litwa",
      incorrect: ["Rosja", null, "Niemcy", "Państwo Osmańskie"],
      type: "closed",
    },
    {
      quest: "Wszystkie drogi prowadzą do?",
      answer: ["Moskwy", "Warszawy", "Londynu", "Rzymu"],
      correct: "Rzymu",
      incorrect: ["Moskwy", "Warszawy", "Londynu", null],
      type: "closed",
    },
    {
      quest: "Zastał drewnianą a zostawił murowaną:",
      answer: [
        "Bolesław Chrobry",
        "Władysław Jagiełło",
        "Kazimierz Wielki",
        "Mieszko I",
      ],
      correct: "Kazimierz Wielki",
      incorrect: ["Bolesław Chrobry", "Władysław Jagiełło", null, "Mieszko I"],
      type: "closed",
    },
    {
      quest: "Wybuch II Wojny Światowej miał miejsce w roku:",
      answer: ["1939", "1945", "1920", "1914"],
      correct: "1939",
      incorrect: [null, "1945", "1920", "1914"],
      type: "closed",
    },
    {
      quest: "Kto został pierwszym prezdyentem Polski?",
      answer: [
        "Lech Wałęsa",
        "Gabriel Narutowicz",
        "Maciej Rataj",
        "Kazimierz Sabbat",
      ],
      correct: "Gabriel Narutowicz",
      incorrect: ["Lech Wałęsa", null, "Maciej Rataj", "Kazimierz Sabbat"],
      type: "closed",
    },
  ],
  coding: [
    {
      quest: "Najpopularniejsza obecnie bilbioteka JS to:",
      answer: ["React", "Angular", "jQuerry", "Vanilla JS"],
      correct: "React",
      incorrect: [null, "Angular", "jQuerry", "Vanilla JS"],
      type: "closed",
    },
    {
      quest: "Div jest elementem",
      answer: ["Block", "Inline", "Graficznym", "Funkcyjnym"],
      correct: "Block",
      incorrect: [null, "Inline", "Graficznym", "Funkcyjnym"],
      type: "closed",
    },
    {
      quest: "const Function = () =>{ return }",
      answer: [
        "Funkcja anonimowa",
        "Funkcja zagnieżdżona",
        "Funkcja logarytmiczna",
        "Funkcja strzałkowa",
      ],
      correct: "Funkcja strzałkowa",
      incorrect: [
        "Funkcja anonimowa",
        "Funkcja zagnieżdżona",
        "Funkcja logarytmiczna",
        null,
      ],
      type: "closed",
    },
    {
      quest: "UseState jest hookiem odpowiedzialnym za",
      answer: [
        "Kontrolę stanu",
        "Render",
        "Wywołanie fukncji",
        "Usunięcie wartości",
      ],
      correct: "Kontrolę stanu",
      incorrect: [null, "Render", "Wywołanie fukncji", "Usunięcie wartości"],
      type: "closed",
    },
    {
      quest: "Który zapis jest poprawny dla listy nienumerycznej?",
      answer: [
        "<ol><li></li></ol>",
        "<li><ul></ul></li>",
        "<ul><li></li></ul>",
        "<ul><li></ul></li>",
      ],
      correct: "<ul><li></li></ul>",
      incorrect: [
        "<ol><li></li></ol>",
        "<li><ul></ul></li>",
        null,
        "<ul><li></ul></li>",
      ],
      type: "closed",
    },
    {
      quest: "Czym jest HOC?",
      answer: [
        "High Order Component",
        "High Obvious Class",
        "Header Of Component",
        "Hookiem",
      ],
      correct: "High Order Component",
      incorrect: [null, "High Obvious Class", "Header Of Component", "Hookiem"],
      type: "closed",
    },
    {
      quest: 'Owrapuj element paragrafowy w diva, a w nim napisz "Done!"',
      answer: null,
      correct: "<div><p>Done!</p></div>",
      type: "input",
    },
    {
      quest: "CSS jest odpowiedzialny za?",
      answer: [
        "Stylowanie",
        "Konstruowanie drzewa DOM",
        "Programowanie funkcyjne",
        "Nic",
      ],
      correct: "Stylowanie",
      incorrect: [
        null,
        "Konstruowanie drzewa DOM",
        "Programowanie funkcyjne",
        "Nic",
      ],
      type: "closed",
    },
    {
      quest:
        "Czy ref pozwala nam odnieść się do konkretnego elementu drzewa DOM?",
      answer: ["Tak, ale tylko dla button", "Nie", "Tak"],
      correct: "Tak",
      incorrect: ["Tak, ale tylko dla button", "Nie", null],
      type: "closed",
    },
    {
      quest: "Aby korzystać z hooków należy go najpierw?",
      answer: [
        "Zaimportować",
        "Zainstalować",
        "Wyeksprotować",
        "Nic nie trzeba robić",
      ],
      correct: "Zaimportować",
      incorrect: [
        null,
        "Zainstalować",
        "Wyeksprotować",
        "Nic nie trzeba robić",
      ],
      type: "closed",
    },
  ],
  culture: [
    {
      quest: "Kim był pierwszy znany polski filozof?",
      answer: ["Witelon", "Kościuszko", "Sokrates", "Homer"],
      correct: "Witelon",
      incorrect: [null, "Kościuszko", "Sokrates", "Homer"],
      type: "closed",
    },
    {
      quest: "Co jest uznawane za sport narodowy w Polsce?",
      answer: ["Siatkówka", "Skoki narciarskie", "Koszykówka", "Piłka nożna"],
      correct: "Piłka nożna",
      incorrect: ["Siatkówka", "Skoki narciarskie", "Koszykówka", null],
      type: "closed",
    },
    {
      quest: "Słynna polska potrawa:",
      answer: ["Pizza", "Kebab", "Pierogi", "Barszcz"],
      correct: "Pierogi",
      incorrect: ["Pizza", "Kebab", null, "Barszcz"],
      type: "closed",
    },
    {
      quest: "Uporządkuj chronologicznie",
      answer: ["Renesans", "Barok", "Pozytywizm", "Oświecenie"],
      correct: ["Renesans", "Barok", "Oświecenie", "Pozytywizm"],
      type: "drag",
    },
    {
      quest: "W której epoce tworzył Adam Mickiewicz",
      answer: ["Młoda Polska", "Pozytywizm", "Romantyzm", "Renesans"],
      correct: "Romantyzm",
      incorrect: ["Młoda Polska", "Pozytywizm", null, "Renesans"],
      type: "closed",
    },
    {
      quest: "Wskaż radio niepubliczne w Polsce",
      answer: ["Jedynka", "RMF FM", "Dwójka", "Polskie Radio 24"],
      correct: "RMF FM",
      incorrect: ["Jedynka", null, "Dwójka", "Polskie Radio 24"],
      type: "closed",
    },
    {
      quest: "Fryderyk Chopin to kompozytor muzyki poważnej pochodzenia",
      answer: ["Polskiego", "Niemieckiego", "Austriackiego", "Helweckiego"],
      correct: "Polskiego",
      incorrect: [null, "Niemieckiego", "Austriackiego", "Helweckiego"],
      type: "closed",
    },
    {
      quest: "Wpisz pierwsze słowa Mazurka Dąbrowskiego (4 słowa)",
      answer: null,
      correct: "Jeszcze Polska nie zginęła",
      type: "input",
    },
    {
      quest: "Kto napisał Pana Tadeusza?",
      answer: null,
      correct: "Adam Mickiewicz",
      type: "input",
    },
    {
      quest: "Dzień matki obchodzimy w Polsce:",
      answer: ["26 maja", "25 maja", "21 maja", "1 czerwca"],
      correct: "26 maja",
      incorrect: [null, "25 maja", "21 maja", "1 czerwca"],
      type: "closed",
    },
  ],
};
